[workspace]
members = [
    "anitors",
    "database",
    "downloader",
    "manager",
    "parser",
    "searcher",
    "server",
    "tmdb"
]
resolver = "2"

[workspace.package]
rust-version = "1.75"
edition = "2021"
license = "GPL-3.0-only"
authors = ["vuhe"]
