[package]
name = "anitors"
version = "0.1.0"
edition = "2021"
description = "基于 Anitomy 的动漫文件名解析器"

[dependencies]
lazy-regex = "3"
chinese-number = { version = "0.7", default-features = false, features = ["std", "chinese-to-number"] }
